dog_pyne_dbt:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('DBT_DATASET_DEV') }}"
      keyfile: /tmp/gcp_key.json
      threads: 4
      location: EU

    prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('DBT_DATASET_PROD') }}"
      keyfile: /tmp/gcp_key.json
      threads: 4
      location: US
